### ISSUE TITLE
YouCompleteMe url not found

### ISSUE THREAD

**Issue by cnasikas** [dionyziz/config#8]
Hi,

I get this error when running `sh install.sh`:

`fatal: No url found for submodule path '.vim/bundle/YouCompleteMe' in .gitmodules`

Thanks a lot

**Comment by cnasikas** [comment]
Ok I run it as `bash install.sh`. The error still exists but the installation proceeded.

**Comment by gtklocker** [comment]
This is an actual issue which should remain open. There are a couple of broken git submodules under `.vim/`.

The reason `sh` failed but `bash` worked is that `sh` probably forced `-e` which fails if any command in the script fails, however this is desirable (and can be forced inside the install script via `set -e`).

**Comment by dionyziz** [comment]
I removed YCM. If there are any more failing submodules let me know.
